{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "CronJob.fullname" . | lower }}
  labels:
    {{- include "CronJob.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "CronJob.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    {{- if .Values.networkPolicy.egress.dns.enabled }}
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
    {{- end }}
    # Allow access to same namespace
    - to:
        - podSelector: {}
    {{- with .Values.networkPolicy.egress.customRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
