apiVersion: v2
name: cronjob
description: Innago Helm Chart for deploying a CronJob
type: application
version: 2.0.2
appVersion: "1.36.1"
icon: https://innago-property-management.github.io/helm-charts/assets/icons/helm.svg
home: https://innago-property-management.github.io/helm-charts/cronjob
sources:
  - https://github.com/innago-property-management/helm-charts/tree/main/charts/cronjob
maintainers:
  - name: "Innago"
    email: "support@innago.com"
keywords:
  - cronjob
  - kubernetes
  - scheduling
  - batch
  - job
annotations:
  artifacthub.io/category: "integration-delivery"
  artifacthub.io/license: "Apache-2.0"
  artifacthub.io/prerelease: "false"
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/innago-property-management/helm-charts/tree/main/charts/cronjob
    - name: Support
      url: https://github.com/innago-property-management/helm-charts/issues
  artifacthub.io/changes: |
    - kind: fixed
      description: "Fix broken Helm icon URL"
