apiVersion: v2
name: registry-container-webhook
description: Kubernetes admission webhook to rewrite container image references for registry caching
type: application
version: 2.0.2
appVersion: "1.16.0"
icon: https://innago-property-management.github.io/helm-charts/assets/icons/helm.svg
home: https://innago-property-management.github.io/helm-charts/registry-container-webhook
sources:
  - https://github.com/innago-property-management/helm-charts/tree/main/charts/registry-container-webhook
  - https://github.com/indeedeng/harbor-container-webhook
maintainers:
  - name: "Innago"
    email: "support@innago.com"
keywords:
  - webhook
  - registry
  - docker
  - harbor
  - caching
  - container
  - admission-controller
annotations:
  artifacthub.io/category: "integration-delivery"
  artifacthub.io/license: "Apache-2.0"
  artifacthub.io/prerelease: "false"
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/innago-property-management/helm-charts/tree/main/charts/registry-container-webhook
    - name: Support
      url: https://github.com/innago-property-management/helm-charts/issues
    - name: Upstream Project
      url: https://github.com/indeedeng/harbor-container-webhook
  artifacthub.io/changes: |
    - kind: fixed
      description: "Fix broken Helm icon URL"

dependencies:
  - name: harbor-container-webhook
    version: 0.8.1
    repository: "https://indeedeng.github.io/harbor-container-webhook"