apiVersion: v2
name: webapp
description: Innago Helm chart for a WebApp in Kubernetes
type: application
version: 2.5.0
appVersion: "2.5.0"
icon: https://cncf-branding.netlify.app/img/projects/helm/icon/color/helm-icon-color.png
