apiVersion: v1
kind: Service
metadata:
  name: {{ include "ValkeyCluster.fullname" . }}-headless
  labels:
    {{- include "ValkeyCluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless
  {{- with .Values.service.headless.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.headless.type }}
  clusterIP: {{ .Values.service.headless.clusterIP }}
  publishNotReadyAddresses: true
  ports:
    - port: 6379
      targetPort: valkey
      protocol: TCP
      name: valkey
    {{- if .Values.cluster.enabled }}
    - port: 16379
      targetPort: cluster-bus
      protocol: TCP
      name: cluster-bus
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "ValkeyCluster.selectorLabels" . | nindent 4 }}
