{{- range .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "WebApp.fullname" $ | lower }}-{{ .name }}
  labels:
    {{- include "WebApp.labels" $ | nindent 4 }}
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}
